name: Build and Deploy React App to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
        working-directory: frontend-react

      - name: Build React app
        run: npm run build
        working-directory: frontend-react

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Netlify
        uses: netlify/actions/cli@v1
        with:
          command: deploy
          args: --prod
          dir: frontend-react/build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: mich-wats-portfolio.netlify.app
